version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Verify setup.py file
          command: |
            if [ ! -f synergy/synergy/setup.py ]; then
              echo "setup.py not found!"
              exit 1
            fi
      - run:
          name: Install dependencies
          command: |
            cd synergy/synergy
            python -m pip install --upgrade pip
            pip install .
      - run:
          name: Lint code
          command: |
            pip install flake8
            flake8 .
      - run:
          name: Run tests
          command: |
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
